### ISSUE TITLE
t/d{1,2}plugin.t tests fail for newer Email::Valid versions

### ISSUE THREAD

**Issue by eserte** [interchange/Dancer-Plugin-DataTransposeValidator#2]
If Email::Valid 1.197 or newer is installed, then tests fail because of unexpected hash keys:

```
#   Failed test 'good result'
#   at t/d1plugin.t line 272.
# Comparing hash keys of $data
# Extra: 'css', 'errors'
```

**Comment by SysPete** [comment]
Hmmm. Just tested here with 1.196, 1.197 and 1.198 without any problems so I'll spin up a new release with extra debug in tests. I'll keep an eye on cpantesters over the next few days. Thanks @eserte for head up.

**Comment by SysPete** [comment]
Aha - mxcheck is failing in travis-ci builds - will just turn that off in tests.
